Repository frog-pond/ccc-server, pull requests merged in 2018-08, with the labels that each got.

#60 St. Olaf streams endpoint
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/index.mjs
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/streams/index.mjs
  package-lock.json
  package.json
Labels: institution:stolaf

#62 Avoid compressing the Docker image cache
  .circleci/config.yml
Labels: ci, enhancement

#65 Minor reorg: extract things from ccc-lib
  modules/node_modules/@frogpond/ccc-bonapp/index.mjs
  modules/node_modules/@frogpond/ccc-bonapp/package.json
  modules/node_modules/@frogpond/ccc-google-calendar/index.mjs
  modules/node_modules/@frogpond/ccc-google-calendar/package.json
  modules/node_modules/@frogpond/ccc-lib/calendar/index.mjs
  modules/node_modules/@frogpond/ccc-lib/feeds/index.mjs
  modules/node_modules/@frogpond/ccc-reason-calendar/index.mjs
  modules/node_modules/@frogpond/ccc-reason-calendar/package.json
  modules/node_modules/@frogpond/ccc-rss-feed/index.mjs
  modules/node_modules/@frogpond/ccc-rss-feed/package.json
  modules/node_modules/@frogpond/ccc-wpjson-feed/index.mjs
  modules/node_modules/@frogpond/ccc-wpjson-feed/package.json
  modules/node_modules/@frogpond/ccci-carleton-college/v1/calendar/index.mjs
  modules/node_modules/@frogpond/ccci-carleton-college/v1/menu/index.mjs
  modules/node_modules/@frogpond/ccci-carleton-college/v1/news/index.mjs
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/calendar/index.mjs
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/menu/index.mjs
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/news/index.mjs
Labels: enhancement

#66 Fix launching
  modules/node_modules/@frogpond/ccc-google-calendar/index.mjs
  modules/node_modules/@frogpond/ccc-reason-calendar/index.mjs
Labels: bug

#68 Clean up the student work information on the server
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/jobs/index.mjs
Labels: enhancement

#67 Stop using --experimental-modules and switch to -r esm
  package-lock.json
  package.json
Labels: enhancement

#72 Deduplicate Student Orgs members lists
  modules/node_modules/@frogpond/ccci-carleton-college/v1/orgs/index.mjs
Labels: institution:carleton

#74 [carleton] fix selector to get Org social links
  modules/node_modules/@frogpond/ccci-carleton-college/v1/orgs/index.mjs
Labels: institution:carleton

#73 expand the env.INSTITUTION check to catch more cases
  modules/node_modules/@frogpond/ccc-server/index.mjs
Labels: enhancement

#75 Add admin link to org type
  modules/node_modules/@frogpond/ccci-carleton-college/v1/orgs/index.mjs
Labels: institution:carleton

#76 Bon-App nutrition endpoint for stolaf and carleton
  modules/node_modules/@frogpond/ccc-bonapp/index.mjs
  modules/node_modules/@frogpond/ccci-carleton-college/v1/index.mjs
  modules/node_modules/@frogpond/ccci-carleton-college/v1/menu/index.mjs
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/index.mjs
  modules/node_modules/@frogpond/ccci-stolaf-college/v1/menu/index.mjs
Labels: institution:carleton, institution:stolaf
